version: '3'
services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env